site_name: Terrable
site_description: Run Terraform APIs locally

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to light mode

nav:
  - Getting started:
    - introduction.md
    - installation.md
