site_name: Terrable
site_description: Run Terraform APIs locally
site_url: https://terrable-dev.github.io/documentation/
repo_url: https://github.com/terrable-dev/terrable

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: purple
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
      
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer

  icon:
    repo: fontawesome/brands/github
nav:
  - Getting started:
    - index.md
    - installation.md
    - writing-handlers.md
  - Terrable CLI:
    - Commands:
      - cli-docs/commands/offline.md
  - Terraform Module:
    - terraform-docs/minimal-config.md
    - terraform-docs/api-gateway.md
    - terraform-docs/api-routes.md
    - terraform-docs/custom-domains.md
    - terraform-docs/custom-policies.md
    - terraform-docs/vpc-assignment.md
    - terraform-docs/environment-variables.md
  - Limitations:
    - limitations.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
