site_name: Terrable
site_description: Run Terraform APIs locally
site_url: https://terrable-dev.github.io/documentation/

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to light mode

nav:
  - Getting started:
    - index.md
    - installation.md
  - Terrable CLI
    - cli-docs/running-locally.md

plugins:
  - termynal
